version: '3'
services:
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    ports:
      - 6379:6379

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:${SURREALDB_VERSION}
    restart: unless-stopped
    command: start
    ports:
      - 8000:8000

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${PG_ADMIN_VERSION}
    restart: unless-stopped
    env_file:
      - .env.pg_admin
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  postgres:
    container_name: postgres
    image: postgres:${PG_VERSION}
    restart: unless-stopped
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - 5432:5432
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data

volumes:
  postgres:
  pgadmin:
