#!/bin/bash

psql -v ON_ERROR_STOP=1 -U postgres  <<-EOSQL
  CREATE ROLE root SUPERUSER CREATEDB LOGIN;
  CREATE ROLE $WHOAMI SUPERUSER CREATEDB LOGIN;

  CREATE DATABASE $WHOAMI OWNER $WHOAMI;
EOSQL
